### ISSUE TITLE
running matlab in script

### ISSUE THREAD

**Issue by mxardre** [Shrediquette/PIVlab#101]
Opening another thread here to avoid messing up the git.

Question
"""
I have a question (and I know it is not the place to put it) but I have 100 of image sequences to run through PIVlab. Using the GUI is perfect to find the PIV parameters, subsequent filtering, field calculation and exporting. But is there a way to run PIVlab with those parameters without PIVlab? Like in a script peaking up each of my image sequences. I read the PIVlab_commandline.m but it does something way cruder than the GUI.
"""

Answer by Shrediquette
"""
Maybe you are looking for this?
https://pivlab.blogspot.com/2022/07/new-in-v257-pivlab-batch-sessions.html
"""

**Comment by mxardre** [comment]
Then I have a question it seems that the box "substract background" is not saved when we save the setting of a session or the session itself. May not be used often as PIVlab is running quite properly without that but could be useful to save it too for script running.

**Comment by Shrediquette** [comment]
Please add questions in the PIVlab forum:
https://groups.google.com/g/pivlab
Github issues is for reporting bugs or proposing enhancements.

**Comment by mxardre** [comment]
Got you about the data. Actually from fiji I was saving some 32-bit float images. And matlab doesnot import it properly. I save them in 16bit it works better.
Thanks a tone
