### ISSUE TITLE
weird value calxy, calu, calv

### ISSUE THREAD

**Issue by mxardre** [Shrediquette/PIVlab#102]
Hello,
I am analysing images with a width of 512px which corresponds to 2.5mm. I do the calibration in the GUI, process the data, and save the session.
When I import the .m of the session in matlab I got a calxy value of  6.8359e-06. I don't see where does it comme from. I would expect either a value of 2.5/512 = 0.0049 or 2.5/15=0.1667. 

If I do the math for calu and calv (time between frame given in the GUI 300s) I got 2.2786e-08. Which alse doesn't match expected calxy values. (but are consistent with the one I import from the .m though) 

Anyone can enlighten these puzzling values?

All the best

**Comment by Shrediquette** [comment]
Can you please check this issue again, I updated something in displaying the calibration values:
https://drive.google.com/file/d/12VyVKYUL3M-f26bRlJJiTVpngYA7cYSB/view?usp=drive_link

**Comment by Shrediquette** [comment]
...and please add further discussion of the beta version here:
#103
