### ISSUE TITLE
Discussion of Beta version PIVlab 3.0

### ISSUE THREAD

**Issue by Shrediquette** [Shrediquette/PIVlab#103]
Let us discuss issues related to the beta in a single github issue.
The beta is avaiable here:
https://drive.google.com/file/d/12VyVKYUL3M-f26bRlJJiTVpngYA7cYSB/view?usp=drive_link
I am changing a lot of stuff in image display, image export and mask generation. This may yield above-average new bugs that I would try to get rid off before releasing the new version.
_**So I am happy about everyone that tests this new version before I release it.**_

**Comment by Shrediquette** [comment]
#102 #100

**Comment by mxardre** [comment]
OK thanks for the rearrangment of the threads. I am following up!

**Comment by mxardre** [comment]
Good! actually the calxy, calu, calv works perfectly fine. I hadn't sleep enough yesterday apparently and I figured out my mistakes.
Cheers
