### ISSUE TITLE
Importing image sequence by name yields wrong order

### ISSUE THREAD

**Issue by dirypan** [Shrediquette/PIVlab#113]
**Describe the bug**
My image sequence is named by time (10.tif is taken at t=1s and 11.tif is taken at t=1.1s etc). Fiji and windows explorer can display the image in the right order, however PIVlab import will sort the first digit then second digit etc, therefore 10.tif will be imported before 6.tif.

**To Reproduce**
Import any image sequence with numerical names.

**Expected behavior**
Image sequence should be sorted by its numerical value.

**Screenshots**
![PixPin_2024-03-01_00-17-50](https://github.com/Shrediquette/PIVlab/assets/15893086/71b55e16-9bfa-4135-8591-c0b713fd1f2e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PIVlab version 2.63
- MATLAB version: tested on 2023a and 2024a pre-release

**Comment by Shrediquette** [comment]
I will check how to fix this!

**Comment by Shrediquette** [comment]
Will be fixed in next release:

- uipickfiles.m, function file_sort, case 1
- Use function natsortfiles: https://de.mathworks.com/matlabcentral/fileexchange/47434-natural-order-filename-sort?s_tid=srchtitle

**Comment by Shrediquette** [comment]
Implemented:
https://github.com/Shrediquette/PIVlab/commit/c909aba9e5d2b557fa65959dafdfc10d78758f7e

It would be great if you download the fixed file and overwrite the file in your local installation to check if it works.
https://github.com/Shrediquette/PIVlab/raw/main/uipickfiles.m

**Comment by dirypan** [comment]
Thank you, just tried, works perfectly.
