### ISSUE TITLE
version: should be 2.37?

### ISSUE THREAD

**Issue by quynhneo** [Shrediquette/PIVlab#16]
https://github.com/Shrediquette/PIVlab/blob/8754e44c7bb4b2b739546ed951940a6a92415ba0/PIVlab_GUI.m#L224

**Comment by Shrediquette** [comment]
Hi, I am new to GitHub and Version control in general. That number that I put into the text file on my Webserver should be the number of the latest "release". I consider the changes I am doing on GitHub as beta tests, once I decide that everything is working and good, I will create another release. This release will then automatically be published on the MATLAB file exchange website (which is most likely the main source for people to download pivlab). Does that make sense? How can these thoughts be included in the code?
Maybe I should convert the string in the remote text file into a number and compare it to the local version. If the local number is higher, then a label "beta" should pop up?

**Comment by quynhneo** [comment]
you should keep a main branch always the latest release, and a development branch (or more than one) where you do the development, testing, fixing certain features. Once you are happy with changes in a development branch, you create a pull request and approve your own pull request to merge into the main branch. Inside matlab, there is away to fetch the release at https://github.com/Shrediquette/PIVlab/releases without manually create a text file somewhere.

**Comment by Shrediquette** [comment]
Thanks for your input! As it seems that you have some experience with all this, can I sometimes ask you git related questions? Could you send me an email, so I have your contact?
I currently am a bit busy with other stuff, so I can't react very quickly to your input, but I will work on it asap.

**Comment by quynhneo** [comment]
Ask away, I will try to answer!
