### ISSUE TITLE
Issue in ANALYZE all frames

### ISSUE THREAD

**Issue by pnvdp** [Shrediquette/PIVlab#47]
Only first frame get analyzed if I do the analyze all frame option, remaining frames didn't analyzed and then I had to do it one by one which is time consuming. Please resolve this.

**Comment by Shrediquette** [comment]
Hi, I don't have this issue, so please send the error message from the command prompt and ideally the images and settings to reproduce the problem. Otherwise I can't do anything.

**Comment by pnvdp** [comment]
[https://drive.google.com/file/d/1xHccJiYqwEywj5nbNLbK6B5PDiJDIw9T/view?usp=sharing](url)
[https://drive.google.com/file/d/11q9aXl2P0G2QmGcPlRqcmdJUp1tjhtRb/view?usp=sharing](url)
Please see the these videos. When I am doing frame by frame it is working but when I am doing analyze all, then it is not. I am inputting a video and this problem happens with any kind of video I upload but there is no problem if I upload frames instead of video.

**Comment by Shrediquette** [comment]
Hi, I can't download the files, but I sent you a request for accessing them via Google drive.

**Comment by Shrediquette** [comment]
...can you please provide the original video data file.

**Comment by pnvdp** [comment]
[https://drive.google.com/file/d/1tjmQe_S7RnufqbWqsWTgbmHCO6PtKEKF/view?usp=sharing](url) 
Please see this.

**Comment by Shrediquette** [comment]
The problem is your video file: It contains 7 identical frames before the next new frame comes. This is not a PIVlab issue.
