### ISSUE TITLE
About the relative error

### ISSUE THREAD

**Issue by ScutLi** [Shrediquette/PIVlab#67]
Hello, I am using your PIVlab code for relevant research. I wanna know where the systematic error of this package comes from and what a number is it. All your help will be highly appreciated.

**Comment by Shrediquette** [comment]
Hi, I did some experiments on this and reported them in my publications:

http://www.rug.nl/research/portal/files/14094707/Chapter_2.pdf

https://openresearchsoftware.metajnl.com/article/view/42/main-text-B43/

https://openresearchsoftware.metajnl.com/articles/10.5334/jors.334/
