### ISSUE TITLE
PIVlab v2.36 - Analyze All Frames

### ISSUE THREAD

**Issue by dlasprugato** [Shrediquette/PIVlab#71]
PIVlab v2.36 - Analyze All Frames
Process stalls exactly at 50%.
Trying to process 1 minute (60s) of UAV (Mavic 2 Pro) video to obtain mean velocity.
Any troubleshooting advice will be much appreciated.
Thank you!
-Dawn

Computer Specs:
Processor	Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz, 2904 Mhz, 8 Core(s), 16 Logical 
64GB RAM

**Comment by Shrediquette** [comment]
You will have the supply the image data.

**Comment by Shrediquette** [comment]
... and why are you using such an old version? Something not working as desired in the newer releases?

**Comment by dlasprugato** [comment]
That version of PIVlab was available with installation of RIVeR.
https://riverdischarge.blogspot.com/p/download.html

**Comment by dlasprugato** [comment]
![Total_Process_50pct](https://user-images.githubusercontent.com/94843017/142865604-e9a97b64-800a-4773-b668-087428571f47.jpg)

**Comment by dlasprugato** [comment]
![PIV_Settings](https://user-images.githubusercontent.com/94843017/142866141-832995b9-2488-4b61-a647-8dd7b0e16a4f.jpg)

**Comment by dlasprugato** [comment]
![PIV_Settings](https://user-images.githubusercontent.com/94843017/142866199-9671a19f-fbc5-45b3-a508-d004785b5e34.jpg)

**Comment by dlasprugato** [comment]
![PIV_Settings](https://user-images.githubusercontent.com/94843017/142866391-c1c4e244-34d7-493a-830a-5a369ca53776.jpg)

**Comment by Shrediquette** [comment]
With "image data" I meant the input data that you want to process in Pivlab

**Comment by dlasprugato** [comment]
There are 3,610 images totaling 2.91 GB.  What's the best way to share that data?

**Comment by Shrediquette** [comment]
Yes Google Drive or OneDrive or Dropbox should work.

**Comment by dlasprugato** [comment]
https://nhcweb-my.sharepoint.com/:f:/p/dlasprugato/EmjijtpUZXZMsHJU5D0GLKMBC8AwrXhYh7GoG5UNf2QYyQ?e=YOwYwq

**Comment by Shrediquette** [comment]
All images within a session must have the same dimensions. This is not the case in your example data.

**Comment by dlasprugato** [comment]
Thank you.  I will look into this issue.  Images were extracted from video frames via RIVeR application.

**Comment by dlasprugato** [comment]
Yes, I see the problem.  I know how this happened.  Thank you very much for being a second set of eyes for this issue!
