### ISSUE TITLE
Better visualize output vector in different colors

### ISSUE THREAD

**Issue by ruinianxu** [Shrediquette/PIVlab#75]
Hey,

This is a great toolbox and I really appreciate your work. If we want to differentiate in and out vectors with different colors, any suggestions which function we should look into? Many thanks!

**Comment by Shrediquette** [comment]
Hi, in PIVlabgui.m go to the function sliderdisp, and then modify the lines that contain quiver

I thin there is a good submission on file exchange for colored vectors.

**Comment by ruinianxu** [comment]
@Shrediquette 
Got it. Thank you so much for your help!
