### ISSUE TITLE
Could multiple graphics options be added in ROI features / correlation function caculation? 

### ISSUE THREAD

**Issue by oleOelo** [Shrediquette/PIVlab#78]
Thanks for such a good tool!

When I was analyzing a vortex inside a droplet, it was found that the inner circular area was bright than the outer circular area because of the limited DOF of my objective, as I focused it on the top of the droplet. I was trying to select the bright area only but this has to be imperfect because the ROI feature only allows us to select a rectangle. Could multiple options be added to ROI features?

Another trivial thing is that sometimes ACF (autocorrelation function) is needed to analyze the correlation length in a multi-vortex pattern, and TCF (time correlation function) is needed to examine the existence period of a vortex in a multi-vortex pattern (known as spatial-temporal two points velocity correlation function). I know there is a ploy-line option but could spatial/temporal correlation function calculation of an ROI option be added?

**Comment by Shrediquette** [comment]
A lot of dynamic masking options are added in version 3.0
