### ISSUE TITLE
image processing processes outside of ROI

### ISSUE THREAD

**Issue by quynhneo** [Shrediquette/PIVlab#87]
When I use GUI, image processing process region outside of ROI. But I don't see the problem in https://github.com/Shrediquette/PIVlab/blob/main/PIVlab_preproc.m

**Comment by Shrediquette** [comment]
Hi, can you give more details? I can't see this, and I wonder why it would be an issue? Because of processing time?

**Comment by Shrediquette** [comment]
No reaction - closing
